import { findFabDocuments } from './fab/fab-source.js?v=20260922-05';
import { parsePdfFile } from './fab/fab-parser.js?v=20260922-05';
import { normalizeTeamName } from './fab/fab-normalizer.js';
import { renderMatches } from './ui/renderer.js';
import { createTemplateCanvas, getTemplatePages } from './ui/instagram-template.js';

const els={refresh:document.querySelector('#refreshFab'),date:document.querySelector('#matchDate'),pdf:document.querySelector('#pdfInput'),status:document.querySelector('#sourceStatus'),message:document.querySelector('#message'),matches:document.querySelector('#matches'),count:document.querySelector('#matchCount'),teamSearch:document.querySelector('#teamSearch'),competitionFilter:document.querySelector('#competitionFilter'),dateFilter:document.querySelector('#dateFilter'),clearFilter:document.querySelector('#clearTeam'),viewCards:document.querySelector('#viewCards'),viewTable:document.querySelector('#viewTable'),selectionBar:document.querySelector('#selectionBar'),selectedCount:document.querySelector('#selectedCount'),clearSelection:document.querySelector('#clearSelection'),generateTemplate:document.querySelector('#generateTemplate'),manualTemplate:document.querySelector('#manualTemplate'),templateModal:document.querySelector('#templateModal'),templatePreview:document.querySelector('#templatePreview'),templatePageInfo:document.querySelector('#templatePageInfo'),templatePageLabel:document.querySelector('#templatePageLabel'),templatePrev:document.querySelector('#templatePrev'),templateNext:document.querySelector('#templateNext'),downloadTemplate:document.querySelector('#downloadTemplate'),closeTemplate:document.querySelector('#closeTemplate'),cancelTemplate:document.querySelector('#cancelTemplate'),addManualMatch:document.querySelector('#addManualMatch'),editorMatches:document.querySelector('#editorMatches'),editorMatchCount:document.querySelector('#editorMatchCount'),templateMainTitle:document.querySelector('#templateMainTitle'),templateSubtitle:document.querySelector('#templateSubtitle')};
let allMatches=[],currentMatches=[],currentPage=1,currentView='cards',editorMatches=[],templatePages=[],currentTemplatePage=0;
const selectedIds=new Set(),templateSettings={title:'HORARIOS BALONCESTO',subtitle:'FEDERADOS'};
function message(text='',visible=Boolean(text)){els.message.textContent=text;els.message.classList.toggle('hidden',!visible)}
function errorText(error){return error instanceof Error?error.message:String(error||'Error desconocido.')}
function normalizeSearch(value){return normalizeTeamName(value).replace(/\s+/g,' ').trim()}
function createMatchId(match){return [match.date,match.time,match.homeTeam,match.awayTeam,match.venue,match.competition].map(normalizeSearch).join('|')}
function createManualMatchId(){return `manual-${Date.now()}-${Math.random().toString(36).slice(2,8)}`}
function withIds(matches){return matches.map(match=>({...match,id:match.id||createMatchId(match)}))}
function updateSelectionUI(){els.selectedCount.textContent=String(selectedIds.size);els.selectionBar.classList.toggle('hidden',selectedIds.size===0);els.generateTemplate.disabled=selectedIds.size===0}
function updateResults(matches,resetPage=false){currentMatches=matches;if(resetPage)currentPage=1;els.count.textContent=`${matches.length} ${matches.length===1?'partido':'partidos'}`;renderMatches(els.matches,matches,{page:currentPage,view:currentView,selectedIds,onPageChange:page=>{currentPage=page;updateResults(currentMatches);els.matches.scrollIntoView({behavior:'smooth',block:'start'})},onToggleSelection:id=>{if(selectedIds.has(id))selectedIds.delete(id);else selectedIds.add(id);updateResults(currentMatches)}});updateSelectionUI()}
function populateFilters(){const competitions=[...new Set(allMatches.map(m=>m.competition).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'es'));const dates=[...new Set(allMatches.map(m=>m.date).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'es'));els.competitionFilter.replaceChildren(new Option('Todas las competiciones',''));competitions.forEach(v=>els.competitionFilter.add(new Option(v,v)));els.dateFilter.replaceChildren(new Option('Todas las fechas',''));dates.forEach(v=>els.dateFilter.add(new Option(v,v)));const enabled=allMatches.length>0;[els.teamSearch,els.competitionFilter,els.dateFilter,els.clearFilter].forEach(el=>el.disabled=!enabled)}
function filterMatches(){const search=normalizeSearch(els.teamSearch.value),competition=els.competitionFilter.value,date=els.dateFilter.value;updateResults(allMatches.filter(match=>{const home=normalizeSearch(match.homeTeam),away=normalizeSearch(match.awayTeam);return(!search||home.includes(search)||away.includes(search))&&(!competition||match.competition===competition)&&(!date||match.date===date)}),true)}
function setMatches(matches){allMatches=withIds(Array.isArray(matches)?matches:[]);selectedIds.clear();populateFilters();filterMatches()}
async function loadFromFab(){const date=els.date.value;if(!date)return;els.refresh.disabled=true;els.refresh.textContent='Buscando…';els.status.textContent=`Buscando jornada del ${date} en la página oficial de horarios de FAB.`;message('Consultando fabasket.com/horarios/ y localizando el enlace de esa jornada…',true);try{const result=await findFabDocuments(date);if(!result.bytes)throw new Error(result.reason||'No se pudo descargar el PDF desde el navegador.');const matches=await parsePdfFile(result.bytes,result.url);setMatches(matches);els.status.textContent=result.source==='fab-horarios'?`Fuente FAB: ${result.label||result.url}`:`Fuente FAB (respaldo): ${result.url}`;message(`Documento de FAB cargado correctamente. Se han extraído ${matches.length} partidos.`,true)}catch(error){console.error(error);els.status.textContent='No se pudo obtener la jornada desde la página de horarios de FAB.';message(`${errorText(error)} Puedes utilizar el PDF manual como alternativa.`,true)}finally{els.refresh.disabled=false;els.refresh.textContent='Buscar en FAB'}}
async function loadLocalPdf(file){if(!file)return;message('Leyendo PDF local…',true);els.status.textContent=`Archivo local: ${file.name}`;try{const bytes=await file.arrayBuffer();const matches=await parsePdfFile(bytes,file.name);setMatches(matches);message(`PDF procesado correctamente. Se han extraído ${matches.length} partidos.`,true)}catch(error){console.error(error);message(`No se ha podido leer el PDF: ${errorText(error)}`,true)}finally{els.pdf.value=''}}
function setView(view){currentView=view;els.viewCards.classList.toggle('active',view==='cards');els.viewTable.classList.toggle('active',view==='table');updateResults(currentMatches)}
function getSelectedMatches(){return allMatches.filter(match=>selectedIds.has(match.id))}
function openTemplateGenerator(){const selected=getSelectedMatches();if(!selected.length)return;openTemplateWithMatches(selected)}
function openManualTemplate(){editorMatches=[];currentTemplatePage=0;templateSettings.title='HORARIOS BALONCESTO';templateSettings.subtitle='FEDERADOS';els.templateMainTitle.value=templateSettings.title;els.templateSubtitle.value=templateSettings.subtitle;renderEditor();rebuildTemplatePages(true);els.templateModal.classList.remove('hidden');document.body.classList.add('modal-open');setTimeout(()=>els.addManualMatch?.focus(),0)}
function openTemplateWithMatches(matches){editorMatches=withIds(matches.map(match=>({...match})));currentTemplatePage=0;els.templateMainTitle.value=templateSettings.title;els.templateSubtitle.value=templateSettings.subtitle;renderEditor();rebuildTemplatePages(true);els.templateModal.classList.remove('hidden');document.body.classList.add('modal-open')}
function makeOrderButton(label,aria,action,disabled=false,extra=''){const b=document.createElement('button');b.type='button';b.className=`editor-order-button ${extra}`.trim();b.textContent=label;b.title=aria;b.setAttribute('aria-label',aria);b.disabled=disabled;b.addEventListener('click',action);return b}
function makeEditorField(label,key,value,index){const wrapper=document.createElement('label');wrapper.className='editor-field';const caption=document.createElement('span');caption.textContent=label;const input=document.createElement('input');input.type='text';input.value=value||'';input.dataset.key=key;input.addEventListener('input',()=>{editorMatches[index][key]=input.value;renderEditorTitle(index);rebuildTemplatePages(false)});wrapper.append(caption,input);return wrapper}
function renderEditorTitle(index){const item=els.editorMatches.querySelector(`[data-index="${index}"]`),match=editorMatches[index],title=item?.querySelector('.editor-match-header strong');if(title&&match)title.textContent=`${match.homeTeam||'Local'} · ${match.awayTeam||'Visitante'}`}
function renderEditor(){els.editorMatchCount.textContent=String(editorMatches.length);els.editorMatches.replaceChildren();if(!editorMatches.length){const empty=document.createElement('div');empty.className='editor-empty';empty.innerHTML='<strong>No hay partidos todavía.</strong><span>Puedes crear un amistoso, torneo o cualquier partido que no aparezca en FAB.</span>';els.editorMatches.appendChild(empty);return}editorMatches.forEach((match,index)=>{const item=document.createElement('article');item.className='editor-match';item.dataset.index=String(index);if(match.id)item.dataset.matchId=match.id;const header=document.createElement('div');header.className='editor-match-header';const number=document.createElement('span');number.className='editor-number';number.textContent=String(index+1).padStart(2,'0');const title=document.createElement('strong');title.textContent=`${match.homeTeam||'Local'} · ${match.awayTeam||'Visitante'}`;const actions=document.createElement('div');actions.className='editor-order-actions';actions.append(makeOrderButton('↑','Subir partido',()=>moveEditorMatch(index,-1),index===0),makeOrderButton('↓','Bajar partido',()=>moveEditorMatch(index,1),index===editorMatches.length-1),makeOrderButton('×','Quitar partido',()=>removeEditorMatch(index),false,'remove'));header.append(number,title,actions);const grid=document.createElement('div');grid.className='editor-fields';grid.append(makeEditorField('Local','homeTeam',match.homeTeam,index),makeEditorField('Visitante','awayTeam',match.awayTeam,index),makeEditorField('Hora','time',match.time,index),makeEditorField('Fecha','date',match.date,index),makeEditorField('Competición','competition',match.competition,index),makeEditorField('Pabellón / pista','venue',match.venue,index));item.append(header,grid);els.editorMatches.appendChild(item)})}
function addManualMatch(){syncEditorLogosToMatches();const date=new Intl.DateTimeFormat('es-ES').format(new Date());editorMatches.push({id:createManualMatchId(),homeTeam:'',awayTeam:'',time:'',date,competition:'AMISTOSO',venue:'',homeLogo:'',awayLogo:''});currentTemplatePage=getTemplatePages(editorMatches).length-1;renderEditor();rebuildTemplatePages(false);requestAnimationFrame(()=>{const last=els.editorMatches.querySelector(`.editor-match[data-index="${editorMatches.length-1}"]`);last?.scrollIntoView({behavior:'smooth',block:'nearest'});last?.querySelector('input[data-key="homeTeam"]')?.focus()})}
function syncEditorLogosToMatches(){editorMatches.forEach((match,index)=>{const item=els.editorMatches.querySelector(`.editor-match[data-index="${index}"]`);if(!item)return;match.homeLogo=item.dataset.logoHome||match.homeLogo||'';match.awayLogo=item.dataset.logoAway||match.awayLogo||''})}
function getPreviewMatches(){syncEditorLogosToMatches();return (templatePages[currentTemplatePage]||[]).map(match=>{const source=editorMatches.find(item=>item.id&&match.id&&item.id===match.id);return source?{...match,homeLogo:source.homeLogo||'',awayLogo:source.awayLogo||''}:{...match}})}
function moveEditorMatch(index,direction){syncEditorLogosToMatches();const target=index+direction;if(target<0||target>=editorMatches.length)return;[editorMatches[index],editorMatches[target]]=[editorMatches[target],editorMatches[index]];currentTemplatePage=Math.min(currentTemplatePage,Math.max(0,getTemplatePages(editorMatches).length-1));renderEditor();rebuildTemplatePages(false)}
function removeEditorMatch(index){syncEditorLogosToMatches();editorMatches.splice(index,1);currentTemplatePage=Math.min(currentTemplatePage,Math.max(0,getTemplatePages(editorMatches).length-1));renderEditor();rebuildTemplatePages(false)}
function rebuildTemplatePages(resetPage=false){syncEditorLogosToMatches();templatePages=getTemplatePages(editorMatches);if(resetPage)currentTemplatePage=0;if(currentTemplatePage>=templatePages.length)currentTemplatePage=Math.max(0,templatePages.length-1);renderTemplatePreview()}
async function renderTemplatePreview(){syncEditorLogosToMatches();const matches=getPreviewMatches();els.templatePreview.replaceChildren();if(matches.length){const loading=document.createElement('div');loading.className='template-preview-loading';loading.textContent='Generando vista previa…';els.templatePreview.appendChild(loading);try{const canvas=await createTemplateCanvas(matches,templateSettings);els.templatePreview.replaceChildren(canvas)}catch(error){console.error(error);const box=document.createElement('div');box.className='template-preview-error';const strong=document.createElement('strong');strong.textContent='No se pudo generar la vista previa.';const span=document.createElement('span');span.textContent=errorText(error);box.append(strong,span);els.templatePreview.replaceChildren(box)}}else{const empty=document.createElement('div');empty.className='template-preview-empty';empty.innerHTML='<strong>La plantilla está vacía.</strong><span>Pulsa «＋ Añadir partido» para empezar.</span>';els.templatePreview.appendChild(empty)}const pageCount=templatePages.length;els.templatePageInfo.textContent=pageCount>1?`${editorMatches.length} partidos · ${pageCount} páginas`:`${editorMatches.length} ${editorMatches.length===1?'partido':'partidos'}`;els.templatePageLabel.textContent=pageCount?`Página ${currentTemplatePage+1} de ${pageCount} · Máximo 8 partidos por imagen`:'Sin partidos';els.templatePrev.disabled=currentTemplatePage===0;els.templateNext.disabled=currentTemplatePage>=pageCount-1||pageCount===0;els.downloadTemplate.disabled=pageCount===0}
function closeTemplateGenerator(){els.templateModal.classList.add('hidden');document.body.classList.remove('modal-open')}
async function downloadCurrentTemplate(){syncEditorLogosToMatches();const matches=getPreviewMatches();if(!matches.length)return;try{const canvas=await createTemplateCanvas(matches,templateSettings);canvas.toBlob(blob=>{if(!blob){message('El navegador no ha podido generar el PNG.',true);return}const url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=`horarios-baloncesto-${currentTemplatePage+1}.png`;document.body.appendChild(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)},'image/png')}catch(error){console.error(error);message(`No se pudo generar el PNG: ${errorText(error)}`,true)}}

els.refresh?.addEventListener('click',loadFromFab);els.pdf?.addEventListener('change',e=>loadLocalPdf(e.target.files?.[0]));els.teamSearch?.addEventListener('input',filterMatches);els.competitionFilter?.addEventListener('change',filterMatches);els.dateFilter?.addEventListener('change',filterMatches);els.clearFilter?.addEventListener('click',()=>{els.teamSearch.value='';els.competitionFilter.value='';els.dateFilter.value='';filterMatches()});els.viewCards?.addEventListener('click',()=>setView('cards'));els.viewTable?.addEventListener('click',()=>setView('table'));els.clearSelection?.addEventListener('click',()=>{selectedIds.clear();updateResults(currentMatches)});els.generateTemplate?.addEventListener('click',openTemplateGenerator);els.manualTemplate?.addEventListener('click',openManualTemplate);els.addManualMatch?.addEventListener('click',addManualMatch);els.closeTemplate?.addEventListener('click',closeTemplateGenerator);els.cancelTemplate?.addEventListener('click',closeTemplateGenerator);els.templateModal?.addEventListener('click',e=>{if(e.target===els.templateModal)closeTemplateGenerator()});els.templatePrev?.addEventListener('click',()=>{if(currentTemplatePage>0){currentTemplatePage--;renderTemplatePreview()}});els.templateNext?.addEventListener('click',()=>{if(currentTemplatePage<templatePages.length-1){currentTemplatePage++;renderTemplatePreview()}});els.downloadTemplate?.addEventListener('click',downloadCurrentTemplate);els.templateMainTitle?.addEventListener('input',()=>{templateSettings.title=els.templateMainTitle.value;renderTemplatePreview()});els.templateSubtitle?.addEventListener('input',()=>{templateSettings.subtitle=els.templateSubtitle.value;renderTemplatePreview()});document.addEventListener('template-distribution-change',()=>renderTemplatePreview());document.addEventListener('template-logo-change',()=>renderTemplatePreview());document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!els.templateModal.classList.contains('hidden'))closeTemplateGenerator()});
updateSelectionUI();
